BEGIN;


CREATE TABLE IF NOT EXISTS public.category_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT category_model_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.client_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT client_model_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.ingredient_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    price_for_one double precision NOT NULL,
    is_deleted boolean NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    category_id bigint,
    storehouse_id bigint,
    quantity integer NOT NULL,
    ingredient_id bigint,
    recipe_id bigint,
    CONSTRAINT ingredient_model_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.order_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    total_cost double precision NOT NULL,
    is_deleted boolean NOT NULL,
    order_date timestamp(6) without time zone,
    client_id bigint,
    CONSTRAINT order_model_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.order_product
(
    product_id bigint NOT NULL,
    order_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.order_readiness
(
    order_id bigint NOT NULL,
    readiness character varying(255) COLLATE pg_catalog."default"
    );

CREATE TABLE IF NOT EXISTS public.product_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    price double precision NOT NULL,
    recipe_id bigint,
    CONSTRAINT product_model_pkey PRIMARY KEY (id),
    CONSTRAINT ukd9g1st9ub0erk31ub1vgvrun3 UNIQUE (recipe_id)
    );

CREATE TABLE IF NOT EXISTS public.recipe_ingredient
(
    recipe_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    CONSTRAINT recipe_ingredient_pkey PRIMARY KEY (recipe_id, ingredient_id)
    );

CREATE TABLE IF NOT EXISTS public.recipe_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL,
    CONSTRAINT recipe_model_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.storehouse_ingredient
(
    storehouse_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    CONSTRAINT storehouse_ingredient_pkey PRIMARY KEY (storehouse_id, ingredient_id)
    );

CREATE TABLE IF NOT EXISTS public.storehouse_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    shelf_number integer NOT NULL,
    total_price double precision NOT NULL,
    ingredient_id bigint,
    CONSTRAINT storehouse_model_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.supplier_ingredient
(
    ingredient_id bigint NOT NULL,
    supplier_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.supplier_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean NOT NULL,
    supplier_address character varying(255) COLLATE pg_catalog."default",
    supplier_email character varying(255) COLLATE pg_catalog."default",
    supplier_name character varying(255) COLLATE pg_catalog."default",
    supplier_phone character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT supplier_model_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.user_model
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    active boolean NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_model_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id bigint NOT NULL,
    roles character varying(255) COLLATE pg_catalog."default"
    );

ALTER TABLE IF EXISTS public.ingredient_model
    ADD CONSTRAINT fk2rnoo88gth1f0mjniakit2b33 FOREIGN KEY (storehouse_id)
    REFERENCES public.storehouse_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredient_model
    ADD CONSTRAINT fkaat7nsxy4axt22f0fvhq2q59u FOREIGN KEY (ingredient_id)
    REFERENCES public.ingredient_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredient_model
    ADD CONSTRAINT fkkkl35989q4gxcpfc4ufm40sqf FOREIGN KEY (recipe_id)
    REFERENCES public.recipe_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredient_model
    ADD CONSTRAINT fkn7lb4h1af0uoif8rdmd4rcw4g FOREIGN KEY (ingredient_id)
    REFERENCES public.recipe_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredient_model
    ADD CONSTRAINT fknxcxvxghhqm94qfjh55bcos6u FOREIGN KEY (category_id)
    REFERENCES public.category_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_model
    ADD CONSTRAINT fkntl3jca7b176fbki45kh5tpga FOREIGN KEY (client_id)
    REFERENCES public.client_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_product
    ADD CONSTRAINT fkd6klbv71q9jh155tqi8cgkq8x FOREIGN KEY (product_id)
    REFERENCES public.order_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_product
    ADD CONSTRAINT fkrjdu6okj5p8bwktmdem7tk679 FOREIGN KEY (order_id)
    REFERENCES public.product_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_readiness
    ADD CONSTRAINT fkaxxfevlmofklhiwynasm8i954 FOREIGN KEY (order_id)
    REFERENCES public.order_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_model
    ADD CONSTRAINT fkigy6rykehsjeb7rwosu2ifxp6 FOREIGN KEY (recipe_id)
    REFERENCES public.recipe_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukd9g1st9ub0erk31ub1vgvrun3
    ON public.product_model(recipe_id);


ALTER TABLE IF EXISTS public.recipe_ingredient
    ADD CONSTRAINT fk3r3a7maarqxot0xgp9lficc9v FOREIGN KEY (recipe_id)
    REFERENCES public.recipe_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.recipe_ingredient
    ADD CONSTRAINT fkpdypv4v0tp3wqxhqusg2sg7pv FOREIGN KEY (ingredient_id)
    REFERENCES public.ingredient_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.storehouse_ingredient
    ADD CONSTRAINT fk5v3854qbl8o1bi7gicj8as0pm FOREIGN KEY (ingredient_id)
    REFERENCES public.ingredient_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.storehouse_ingredient
    ADD CONSTRAINT fkss9t3k1dfno3fq4vwuerq3r1f FOREIGN KEY (storehouse_id)
    REFERENCES public.storehouse_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.storehouse_model
    ADD CONSTRAINT fkour9n2016kubfk0jw3jxy5f18 FOREIGN KEY (ingredient_id)
    REFERENCES public.ingredient_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.supplier_ingredient
    ADD CONSTRAINT fk68ngmuu9xyin8851ffjfl1ib3 FOREIGN KEY (supplier_id)
    REFERENCES public.ingredient_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.supplier_ingredient
    ADD CONSTRAINT fklot6y5vcr4sx3jh2g3ub4utei FOREIGN KEY (ingredient_id)
    REFERENCES public.supplier_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fkryojaj4bpgbcrlxbtdbejvwn FOREIGN KEY (user_id)
    REFERENCES public.user_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;